# WARNING - Generated by {fusen} from dev/flat_minimal_package.Rmd: do not edit by hand

test_that("URL returns a successful response code", {
    library(httr)
  
    url <- "https://data.baseball.computer/dbt/bc_remote.db"  # Replace with your URL
  
    # Make the HTTP request
    response <- httr::GET(url)
    
    # Check if the response code is 200 (OK)
    expect_equal(httr::http_status(response)$category, "Success")
})
