# WARNING - Generated by {fusen} from dev/flat_minimal_package.Rmd: do not edit by hand

#' create_con Title
#' @description This function creates a connection to a local database file on disk.
#' @return 1
#' @export
#' @importFrom DBI dbConnect dbExecute
#' @importFrom duckdb duckdb
#' 

create_con <- function() {
    # Create a database file on disk
    con <- dbConnect(duckdb(), dbdir = "retro_baseball_stats.db")
    
    return(con)
}
