# WARNING - Generated by {fusen} from dev/flat_minimal_package.Rmd: do not edit by hand

#' download_create_local_database Title
#' @description This function downloads a database file from a remote location and creates a connection to it.
#' @return 1
#' @export
#' @importFrom DBI dbConnect dbExecute
#' 
download_create_local_database <- function(con) {
    # Create a database file on disk

    # Enable remote access
    dbExecute(con, "INSTALL httpfs")
    dbExecute(con, "LOAD httpfs")
    # This ATTACH command only needs to be run once on an existing database and will fail
    # if run twice, but you can safely ignore the error in that case
    dbExecute(con, "ATTACH 'https://data.baseball.computer/dbt/bc_remote.db' (READ_ONLY)")
    dbExecute(con, "USE bc_remote")
    dbExecute(con, "USE main_models")
}
