# WARNING - Generated by {fusen} from dev/flat_minimal_package.Rmd: do not edit by hand

#' fetch_player_stats Title
#'
#' @return 1
#' @export
#'

fetch_player_stats <- function(con, table_name, columns) {
  # Construct the SQL query
  query <- sprintf(
    "SELECT %s FROM %s",
    paste(columns, collapse = ", "),
    table_name
  )
  
  # Execute the query
  data <- dbGetQuery(con, query)
  return(data)
}
